backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: settings
    label: Site Settings
    files:
      - label: Contact Information
        name: contact
        file: data/contact.json
        fields:
          - {label: Phone Number, name: phone, widget: string, default: "9177 2688"}
          - {label: WeChat, name: wechat, widget: string, default: "a91772688"}
          - {label: Email, name: email, widget: string}

  - name: properties
    label: Properties
    folder: data/properties
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Status, name: status, widget: select, options: [sold, rented, available]}
      - {label: Price, name: price, widget: string}
      - {label: Description, name: body, widget: markdown}

  - name: testimonials
    label: Testimonials
    folder: data/testimonials
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Client Name, name: name, widget: string}
      - {label: Testimonial, name: content, widget: text}
